import { errorCounter } from './metrics.ts';
import { sendEmail } from '../services/emailService.ts';
import { env } from './env.ts';
import logger from './logger.ts';
import os from 'os';
import { db } from '../../db/schema.ts';
import { sql as drizzleSql } from 'drizzle-orm';
import { redisClient } from './redis.ts';
import { getPdfServiceConfig } from './pdfQueue.ts';

export interface SystemAlert {
  id: string;
  type: 'API_KEY_FAILURE' | 'PAYMENT_FAILURE' | 'HIGH_ERROR_RATE' | 'LATENCY_SPIKE' | 'SYSTEM_DEGRADED';
  severity: 'critical' | 'warning';
  summary: string;
  details: string;
  timestamp: Date;
}

// Keep a lightweight historical log of triggered alerts in memory
const alertHistory: SystemAlert[] = [];
const MAX_ALERT_HISTORY = 100;

// Throttling configuration for admin email alerts
const emailThrottles: Record<string, number> = {};
const EMAIL_THROTTLE_MS = 5 * 60 * 1000; // at most 1 email per type ever 5 minutes

// Sliding window for general errors detection
const errorTimestamps: number[] = [];
const ERROR_RATE_THRESHOLD = 15; // >15 errors in last 5 minutes
const SLIDING_WINDOW_MS = 5 * 60 * 1000; // 5 minutes

/**
 * Triggers a system alert.
 * Logs the issue, stores it in alert history, and emails the administrator if rate limits permit.
 */
export async function triggerAlert(
  type: SystemAlert['type'],
  severity: SystemAlert['severity'],
  summary: string,
  details: string
) {
  const id = `alert_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  const alert: SystemAlert = {
    id,
    type,
    severity,
    summary,
    details,
    timestamp: new Date()
  };

  // Add to history
  alertHistory.unshift(alert);
  if (alertHistory.length > MAX_ALERT_HISTORY) {
    alertHistory.pop();
  }

  // Structured Log
  const logMessage = `[SYSTEM_ALERT] severity=${severity} type=${type} summary="${summary}"`;
  if (severity === 'critical') {
    logger.error(logMessage, { alert });
  } else {
    logger.warn(logMessage, { alert });
  }

  // Email Notification with Throttling
  const adminEmail = env.ADMIN_EMAIL;
  if (adminEmail) {
    const lastSent = emailThrottles[type] || 0;
    const now = Date.now();
    if (now - lastSent >= EMAIL_THROTTLE_MS) {
      emailThrottles[type] = now;
      
      const emailSubject = `[CareerCraft Alert] [${severity.toUpperCase()}] ${summary}`;
      const emailHtml = `
        <div style="font-family: sans-serif; padding: 20px; border-radius: 8px; border: 1px solid #e2e8f0; max-width: 600px;">
          <h2 style="color: ${severity === 'critical' ? '#dc2626' : '#d97706'}; border-bottom: 2px solid #f1f5f9; padding-bottom: 10px;">
            ⚠️ System Alarm Notification
          </h2>
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #475569; width: 120px;">Alert Type:</td>
              <td style="padding: 8px 0; font-family: monospace; color: #1e293b;">${type}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #475569;">Severity:</td>
              <td style="padding: 8px 0; text-transform: uppercase; font-weight: bold; color: ${severity === 'critical' ? '#dc2626' : '#d97706'}">${severity}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #475569;">Occurred:</td>
              <td style="padding: 8px 0; color: #1e293b;">${alert.timestamp.toISOString()}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #475569;">Summary:</td>
              <td style="padding: 8px 0; font-weight: bold; color: #0f172a;">${summary}</td>
            </tr>
          </table>
          <div style="margin-top: 20px; padding: 15px; background-color: #f8fafc; border-radius: 6px; border: 1px solid #e2e8f0;">
            <p style="margin: 0 font-weight: bold; color: #334155; margin-bottom: 5px;">Error Details:</p>
            <pre style="margin: 0; font-family: monospace; font-size: 13px; color: #0f172a; white-space: pre-wrap; word-break: break-all;">${details}</pre>
          </div>
          <p style="margin-top: 25px; font-size: 11px; color: #94a3b8; border-top: 1px solid #f1f5f9; padding-top: 15px; text-align: center;">
            This is an automated alert generated by the custom CareerCraft Monitoring service. Throttling is active; next notification for ${type} is blocked for 5 minutes.
          </p>
        </div>
      `;

      // Async fire and forget so we don't delay the main thread
      sendEmail({
        to: adminEmail,
        subject: emailSubject,
        html: emailHtml,
        text: `[${severity.toUpperCase()}] ${summary}\n\nType: ${type}\nDate: ${alert.timestamp.toISOString()}\nDetails: ${details}`
      }).catch(err => {
        logger.error('[AlertService] Failed sending alert email to admin', { error: err.message });
      });
    }
  }
}

/**
 * Hook to record general error events.
 * Handles prometheus metrics increment AND detects high overall error rates in a rolling sliding window,
 * plus triggers proactive alarms for critical failures (payment errors, API key issues).
 */
export function trackError(type: string, code: string, details?: any) {
  // 1. Prometheus Metrics Increment
  errorCounter.inc({ type, code });

  const errorString = details instanceof Error 
    ? details.stack || details.message 
    : typeof details === 'object' 
      ? JSON.stringify(details) 
      : String(details || '');

  // 2. Specific Alarms Handling
  if (type === 'ai_error' && (code === 'AI_CONFIG_ERROR' || code === 'AI_SERVICE_LIMITED' && errorString.toLocaleLowerCase().includes('api key'))) {
    triggerAlert(
      'API_KEY_FAILURE',
      'critical',
      'Gemini AI API Key failure or authentication credentials issue',
      `The system received an API key error when calling the AI engine (Code: ${code}).\n\nStack Trace/Details:\n${errorString}`
    );
  } else if (type === 'payment_error' || type === 'webhook_error') {
    const isWebhookSignature = code === 'signature_verification_failed';
    const alarmSeverity = isWebhookSignature ? 'warning' : 'critical';
    triggerAlert(
      'PAYMENT_FAILURE',
      'critical', // Ensure major payment processing failures raise Critical alerts
      `Stripe checkout or webhook transaction failure: ${code}`,
      `A checkout session or Stripe webhook event failed in production (Type: ${type}, Code: ${code}).\n\nPayload:\n${errorString}`
    );
  }

  // 3. Rolling Window Error Counter
  const now = Date.now();
  errorTimestamps.push(now);

  // Clean elements older than SLIDING_WINDOW_MS
  const limit = now - SLIDING_WINDOW_MS;
  while (errorTimestamps.length > 0 && errorTimestamps[0] < limit) {
    errorTimestamps.shift();
  }

  if (errorTimestamps.length > ERROR_RATE_THRESHOLD) {
    triggerAlert(
      'HIGH_ERROR_RATE',
      'critical',
      `High application error rate detected! (${errorTimestamps.length} errors)`,
      `The app registered ${errorTimestamps.length} exceptions in the last 5 minutes, exceeding the threshold of ${ERROR_RATE_THRESHOLD}.\n\nLast Error Details:\nType: ${type}, Code: ${code}\nDetails:\n${errorString}`
    );
    // Flush to prevent spam
    errorTimestamps.length = 0;
  }
}

/**
 * Returns latest alert notifications history.
 */
export function getAlertHistory() {
  return alertHistory;
}

/**
 * Compiles a full performance metrics, system load, resource utilization, and health report.
 */
export async function compileHealthReport() {
  // OS and Process stats
  const uptime = process.uptime();
  const memoryUsage = process.memoryUsage();
  
  // CPU usage calculation
  const cpuUsage = process.cpuUsage();
  const systemLoad = os.loadavg();
  const totalMemory = os.totalmem();
  const freeMemory = os.freemem();

  // Test Database Connection
  let dbStatus = 'DOWN';
  let dbLatencyMs = 0;
  try {
    const start = Date.now();
    await db.execute(drizzleSql`SELECT 1`);
    dbLatencyMs = Date.now() - start;
    dbStatus = 'UP';
  } catch (err: any) {
    dbStatus = `DOWN: ${err?.message || err}`;
    triggerAlert('SYSTEM_DEGRADED', 'critical', 'Database connectivity failure', `The application fails to communicate with the SQL database:\n${err?.message || err}`);
  }

  // Test Redis connection status
  let redisStatus = 'NOT_CONFIGURED';
  if (redisClient) {
    redisStatus = redisClient.isReady ? 'UP' : 'DOWN';
    if (!redisClient.isReady && env.NODE_ENV === 'production') {
      triggerAlert('SYSTEM_DEGRADED', 'critical', 'Production Redis disconnection', 'The production Redis client is not active.');
    }
  }

  const pdfConfig = await getPdfServiceConfig();

  const keysConfigured = {
    DATABASE_URL: !!env.DATABASE_URL,
    REDIS_URL: !!env.REDIS_URL,
    GEMINI_API_KEY: !!process.env.GEMINI_API_KEY,
    STRIPE_SECRET_KEY: !!env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: !!env.STRIPE_WEBHOOK_SECRET,
    EMAIL_API_KEY: !!process.env.EMAIL_API_KEY,
    JWT_SECRET: !!env.JWT_SECRET,
  };

  return {
    status: dbStatus === 'UP' && (redisStatus === 'UP' || redisStatus === 'NOT_CONFIGURED') ? 'HEALTHY' : 'DEGRADED',
    timestamp: new Date(),
    uptime,
    metrics: {
      memory: {
        rss: memoryUsage.rss,
        heapTotal: memoryUsage.heapTotal,
        heapUsed: memoryUsage.heapUsed,
        external: memoryUsage.external,
        systemTotalBytes: totalMemory,
        systemFreeBytes: freeMemory,
        usagePercentage: Math.round(((totalMemory - freeMemory) / totalMemory) * 100)
      },
      cpu: {
        usage: cpuUsage,
        systemLoad1m: systemLoad[0],
        systemLoad5m: systemLoad[1],
        systemLoad15m: systemLoad[2],
        coresCount: os.cpus().length
      },
      database: {
        status: dbStatus,
        latencyMs: dbLatencyMs,
        provider: env.DATABASE_URL ? 'PostgreSQL' : 'PGlite'
      },
      redis: {
        status: redisStatus
      },
      pdf: {
        serviceType: pdfConfig.serviceType,
        serviceUrl: pdfConfig.serviceUrl,
        isConfigured: pdfConfig.serviceType === 'puppeteer' || !!pdfConfig.serviceUrl
      }
    },
    keysConfigured,
    alerts: alertHistory
  };
}
